/**
 * SVG export: one stock sheet as a standalone file.
 *
 * Renders the *same* component the screen draws, through `react-dom/server`,
 * rather than building a second copy of the drawing as a string. `SheetFigure`
 * already knows where every part, kerf line, and label goes; a headless string
 * builder would be a second answer to that question, and the two would drift
 * apart the first time either changed. `react-dom/server` ships inside the
 * `react-dom` package the app already depends on, so this costs no bundle size
 * and adds no dependency.
 *
 * `src/export/` may depend on `src/ui/` renderers. The reverse direction, and
 * any dependency from `domain/` or `solver/` on either, stays forbidden.
 *
 * The exported drawing carries its physical size in millimetres. Millimetres
 * rather than the user's display unit because mm is the canonical internal unit
 * and the file is dimensionally identical either way - only the number written
 * in the attribute differs. Labels *inside* the drawing still follow the user's
 * display unit, because those a person reads. DXF is the opposite case and sets
 * `$INSUNITS` from the display unit, since there the unit is a document-level
 * declaration a CAD user acts on.
 */

import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import type { CutPlan } from '../domain/cutplan';
import type { Layout, Material, Part, SolverConfig, Stock } from '../domain/types';
import { figureViewBox, SheetFigure } from '../ui/components/SheetFigure';
import { PRINT_THEME } from '../ui/components/sheetTheme';
import type { DisplayUnit } from '../ui/state/types';

export interface SheetExportInput {
  layout: Layout;
  stock: Stock;
  parts: Part[];
  material: Material;
  config: SolverConfig;
  displayUnit: DisplayUnit;
  fractionDenominator: number;
  /** 1-based position among the sheets being exported, for the title block. */
  sheetNumber: number;
  sheetCount: number;
  /** Cut-plan overlays, off unless a plan is supplied and asked for. */
  cutPlan?: CutPlan | null;
  showCutLines?: boolean;
  showPartNumbers?: boolean;
  /** Injectable so tests are not time-dependent. */
  generatedAt?: Date;
}

/**
 * Render one sheet as a complete, standalone SVG document.
 *
 * Uses the print palette rather than the dark screen theme: this file is going
 * to paper, to Inkscape, or to a CNC shop, and none of those want a dark
 * background.
 */
export function renderSheetSvg(input: SheetExportInput): string {
  const viewBox = figureViewBox(input.stock, true);

  const markup = renderToStaticMarkup(
    createElement(SheetFigure, {
      layout: input.layout,
      stock: input.stock,
      parts: input.parts,
      material: input.material,
      config: input.config,
      displayUnit: input.displayUnit,
      fractionDenominator: input.fractionDenominator,
      theme: PRINT_THEME,
      showTitle: true,
      sheetNumber: input.sheetNumber,
      sheetCount: input.sheetCount,
      paintBackground: true,
      width: `${formatMm(viewBox.width)}mm`,
      height: `${formatMm(viewBox.height)}mm`,
      cutPlan: input.cutPlan ?? null,
      showCutLines: input.showCutLines ?? false,
      showPartNumbers: input.showPartNumbers ?? false,
    }),
  );

  return `<?xml version="1.0" encoding="UTF-8"?>\n${metadataComment(input)}\n${markup}\n`;
}

/**
 * Provenance for whoever opens the file later, including the saw settings the
 * layout assumed. A drawing that does not say what kerf it was packed for
 * cannot be re-cut with confidence on a different blade.
 */
function metadataComment(input: SheetExportInput): string {
  const generated = (input.generatedAt ?? new Date()).toISOString();
  const lines = [
    'Generated by Cutz - cut list optimizer',
    `material: ${input.material.name} (${formatMm(input.material.thickness)}mm)`,
    `sheet: ${input.sheetNumber} of ${input.sheetCount}`,
    `stock: ${formatMm(input.stock.width)} x ${formatMm(input.stock.height)} mm`,
    `kerf: ${formatMm(input.config.kerf)}mm, edge trim: ${formatMm(input.config.edgeTrim)}mm`,
    `waste: ${(input.layout.wastePct * 100).toFixed(1)}%`,
    `generated: ${generated}`,
  ];
  return `<!--\n  ${lines.map(xmlCommentSafe).join('\n  ')}\n-->`;
}

/**
 * `--` cannot appear inside an XML comment, and a material named "18mm --
 * seconds" would otherwise produce a file no parser will open.
 */
function xmlCommentSafe(text: string): string {
  return text.replace(/--+/g, '-').replace(/-$/, '');
}

/**
 * Millimetres with float noise trimmed.
 *
 * Unit conversion leaves values like `1219.2000000000002`, and a viewer showing
 * that as the sheet width makes the whole export look untrustworthy. Six
 * decimals is well inside `geometry.EPSILON`, so this can only ever drop noise.
 */
function formatMm(mm: number): string {
  return Number.parseFloat(mm.toFixed(6)).toString();
}

export interface SheetFileNameInput {
  /** 1-based, matching the sheet tabs in the UI. */
  sheetNumber: number;
  material: Material;
  extension: 'svg' | 'dxf';
}

/**
 * `cutz-sheet-2-18mm-birch-ply.svg`.
 *
 * Project names arrive with IndexedDB persistence in M6 and will slot in ahead
 * of the sheet number.
 */
export function sheetFileName({ sheetNumber, material, extension }: SheetFileNameInput): string {
  const slug = slugify(material.name);
  return slug
    ? `cutz-sheet-${sheetNumber}-${slug}.${extension}`
    : `cutz-sheet-${sheetNumber}.${extension}`;
}

/** Lowercase ASCII, single dashes, no leading or trailing dash. */
function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}
